// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: ProcessCommand.capnp

#ifndef CAPNP_INCLUDED_c0f7398d39bb2416_
#define CAPNP_INCLUDED_c0f7398d39bb2416_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 6001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include <capnzero/ID.capnp.h>

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(af21842ecc7a1df7);
CAPNP_DECLARE_SCHEMA(c0be79f8446c51c2);
enum class Cmd_c0be79f8446c51c2: uint16_t {
  START,
  STOP,
};
CAPNP_DECLARE_ENUM(Cmd, c0be79f8446c51c2);

}  // namespace schemas
}  // namespace capnp

namespace capnzero {

struct ProcessCommand {
  ProcessCommand() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::Cmd_c0be79f8446c51c2 Cmd;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(af21842ecc7a1df7, 1, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class ProcessCommand::Reader {
public:
  typedef ProcessCommand Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::capnzero::ProcessCommand::Cmd getCommand() const;

  inline bool hasReceiverID() const;
  inline  ::capnzero::ID::Reader getReceiverID() const;

  inline bool hasRobotIDs() const;
  inline  ::capnp::List< ::capnzero::ID>::Reader getRobotIDs() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ProcessCommand::Builder {
public:
  typedef ProcessCommand Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::capnzero::ProcessCommand::Cmd getCommand();
  inline void setCommand( ::capnzero::ProcessCommand::Cmd value);

  inline bool hasReceiverID();
  inline  ::capnzero::ID::Builder getReceiverID();
  inline void setReceiverID( ::capnzero::ID::Reader value);
  inline  ::capnzero::ID::Builder initReceiverID();
  inline void adoptReceiverID(::capnp::Orphan< ::capnzero::ID>&& value);
  inline ::capnp::Orphan< ::capnzero::ID> disownReceiverID();

  inline bool hasRobotIDs();
  inline  ::capnp::List< ::capnzero::ID>::Builder getRobotIDs();
  inline void setRobotIDs( ::capnp::List< ::capnzero::ID>::Reader value);
  inline  ::capnp::List< ::capnzero::ID>::Builder initRobotIDs(unsigned int size);
  inline void adoptRobotIDs(::capnp::Orphan< ::capnp::List< ::capnzero::ID>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::capnzero::ID>> disownRobotIDs();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ProcessCommand::Pipeline {
public:
  typedef ProcessCommand Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::capnzero::ID::Pipeline getReceiverID();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::capnzero::ProcessCommand::Cmd ProcessCommand::Reader::getCommand() const {
  return _reader.getDataField< ::capnzero::ProcessCommand::Cmd>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnzero::ProcessCommand::Cmd ProcessCommand::Builder::getCommand() {
  return _builder.getDataField< ::capnzero::ProcessCommand::Cmd>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ProcessCommand::Builder::setCommand( ::capnzero::ProcessCommand::Cmd value) {
  _builder.setDataField< ::capnzero::ProcessCommand::Cmd>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool ProcessCommand::Reader::hasReceiverID() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ProcessCommand::Builder::hasReceiverID() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnzero::ID::Reader ProcessCommand::Reader::getReceiverID() const {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnzero::ID::Builder ProcessCommand::Builder::getReceiverID() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::capnzero::ID::Pipeline ProcessCommand::Pipeline::getReceiverID() {
  return  ::capnzero::ID::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void ProcessCommand::Builder::setReceiverID( ::capnzero::ID::Reader value) {
  ::capnp::_::PointerHelpers< ::capnzero::ID>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnzero::ID::Builder ProcessCommand::Builder::initReceiverID() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ProcessCommand::Builder::adoptReceiverID(
    ::capnp::Orphan< ::capnzero::ID>&& value) {
  ::capnp::_::PointerHelpers< ::capnzero::ID>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnzero::ID> ProcessCommand::Builder::disownReceiverID() {
  return ::capnp::_::PointerHelpers< ::capnzero::ID>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ProcessCommand::Reader::hasRobotIDs() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool ProcessCommand::Builder::hasRobotIDs() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::capnzero::ID>::Reader ProcessCommand::Reader::getRobotIDs() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::capnzero::ID>::Builder ProcessCommand::Builder::getRobotIDs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void ProcessCommand::Builder::setRobotIDs( ::capnp::List< ::capnzero::ID>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::capnzero::ID>::Builder ProcessCommand::Builder::initRobotIDs(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void ProcessCommand::Builder::adoptRobotIDs(
    ::capnp::Orphan< ::capnp::List< ::capnzero::ID>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::capnzero::ID>> ProcessCommand::Builder::disownRobotIDs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::capnzero::ID>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

}  // namespace

#endif  // CAPNP_INCLUDED_c0f7398d39bb2416_
